<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
    <PackageReference Include="Sdcb.FFmpeg" Version="7.0.0" />
    <PackageReference Include="Sdcb.FFmpeg.runtime.windows-x64" Version="7.0.0" />
  </ItemGroup>

</Project>
