<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReceiverLib.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Protocol/Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sdcb.FFmpeg" Version="7.0.0" />
    <PackageReference Include="Sdcb.FFmpeg.runtime.windows-x64" Version="7.0.0" />
  </ItemGroup>

</Project>
